version: "3"
services:
  nextjs-focus-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      - NODE_ENV=production
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env